mysite/urls.py
from django.contrib import admin
from django.urls import include, path
from open_now.views import LoginView

urlpatterns = [
    path('',LoginView.as_view(), name='login'),
    path('admin/', admin.site.urls),
    path('accounts/', include('allauth.urls')),
    path('open_now/', include('open_now.urls')),
    path('accounts/open_now/', include('open_now.urls')),
]

open_now/urls.py
from django.urls import path

from . import views

app_name = 'open_now'

urlpatterns = [
    path('', views.LoginView.as_view(), name='login'),
    path('home/', views.HomeView.as_view(), name='home'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('businesses/', views.BusinessView.as_view(), name='business_list'),
    path('business-form/', views.BusinessFormView.as_view(), name='business_form'),
    path('new-business/', views.get_business, name='new_business'),
    path('search/', views.search_business, name='search_result'),
    path('new-forum/', views.new_forum, name='new_forum'),
    path('forums/', views.forums, name='forums'),
    path('forums/<int:pk>/', views.discuss, name='discuss'),
    path('new-discussion/', views.new_discussion, name='new_discussion'),
    path('businesses/<str:business_name>/', views.business_specs, name='business_specs'),
    path('new-review/', views.get_review, name='new_review'),
    path('update-hours/', views.get_hours, name='update_hours'),
    path('map/', views.location_view, name='map'),
    path('map/display/', views.map_view, name='map-view'),



]

open_now/forms.py
from django.forms import ModelForm
from .models import *
from django import forms
 
class CreateInForum(ModelForm):
    class Meta:
        model= Forum
        fields = ['topic', 'description']
 
class CreateInDiscussion(ModelForm):
    class Meta:
        model= Discussion
        fields = ['discuss']

class CreateInHours(ModelForm):
    class Meta:
        model= OpeningHours
        fields = ["weekday_from", "weekday_to", "from_hour", "to_hour"]
        
class LocationForm(ModelForm):
	class Meta:
		model = Location
		fields = ['street_address', 'address_2', 'city', 'state', 'postal_code']

class SearchForm(ModelForm):
	class Meta:
		model = Search
		fields = ['search_category', 'radius']

"""class BusinessImageForm(ModelForm):
    class Meta:
        model = Business
        fields = ['business_image']
        widgets = {'business_image': forms.ClearableFileInput(attrs={'class': 'form-control mt-2 mb-4'})}"""

class CreateBusinessForm(ModelForm):
    class Meta:
        model = Business
        fields = ['business_name','description','website','phone_number','business_category']

open_now/views.py
from django.shortcuts import render

from django.db import models
from django.shortcuts import get_object_or_404, render
from django.http import HttpResponse
from django.template import loader
from .models import Business, Forum, Discussion
from django.urls import reverse, reverse_lazy
from django.http import HttpResponse, HttpResponseRedirect
from .forms import * 
from django.shortcuts import redirect, render
from django.views.generic import CreateView
from django.views import generic
from geopy.geocoders import Nominatim
from geopy.distance import geodesic
from .utils import *
import folium
from django.urls import path
from .models import Login


def login(request):
    return render(request, 'open_now/login.html')


class LoginView(generic.ListView):
    template_name = 'open_now/login.html'

    def get_queryset(self):
        """
        """
        return

class HomeView(generic.ListView):
    template_name = 'open_now/home.html'

    def get_queryset(self):
        """
        """
        return

class AboutView(generic.ListView):
    template_name = 'open_now/about.html'

    def get_queryset(self):
        """
        """
        return

class BusinessView(generic.ListView):
    template_name = 'open_now/business_list.html'
    context_object_name = 'business_list'

    def get_queryset(self):
        """
        """
        return Business.objects.all()
        return

class BusinessFormView(generic.CreateView):
    model = Business
    template_name = 'open_now/business_form.html'
    fields = ('business_name','description','website','phone_number','business_category')
    def get_success_url(self):
        return reverse('open_now:business_list')
    def get_queryset(self):
        """
        """
        return

def get_business(request):

    business_name = request.POST['business_name']
    description = request.POST['description']
    phone_number = request.POST['phone_number']
    website = request.POST['website']
    business_category = request.POST['business_category']
    t = Business(business_name=business_name,description=description, phone_number = phone_number, website = website,
                 business_category = business_category)
    t.save()
    return HttpResponseRedirect(reverse('open_now:business_list'))

def search_business(request):
    srh = request.GET['query'].lower().strip()
    businesses = Business.objects.filter(business_name__icontains=srh) | Business.objects.filter(description__icontains=srh) | Business.objects.filter(business_category__icontains=srh)
    params={'businesses': businesses, 'search':srh}
    return render(request, 'open_now/search_business.html', params)

def new_forum(request):
    
    form = CreateInForum()
    if request.method == 'POST':
        forum = Forum(email = request.user)
        form = CreateInForum(request.POST, instance=forum)
        if form.is_valid():
            forum.save()
            return redirect('/open_now/forums')
    context ={'form':form}
    return render(request,'open_now/new_forum.html',context)
    # email=request.user.email
    # topic= request.POST['topic']
    # description = request.POST['description']
    # newForum = Forum(email=email, topic=topic, description=description)
    # newForum.save()
    # return HttpResponseRedirect(reverse('open_now:forums'))
    

def discuss(request, pk):
    discussion = Forum.objects.get(id=pk)

    context = {'f': discussion}

    return render(request, 'open_now/new_discussion.html', context)
 
def new_discussion(request):
    # user = request.user
    discuss = request.POST['discuss']
    forum_topic = request.POST['forum']
    forum = Forum.objects.get(id=forum_topic)
    newDiscuss = Discussion(forum=forum ,discuss=discuss, email = request.user)
    newDiscuss.save()
    return HttpResponseRedirect(reverse('open_now:forums'))

def forums(request):
    all_forums=Forum.objects.all()
    count=all_forums.count()
    discussions=[]
    for i in all_forums:
        discussions.append(i.discussion_set.all())
 
    context={'forums':all_forums,
            'count':count,
            'discussions':discussions}
    return render(request,'open_now/forums.html',context)


def business_specs(request, business_name):
    business = Business.objects.get(business_name__startswith=business_name)

    context = {'business': business, 'reviews': business.review_set.all(), 'hours': business.openinghours_set.last()}

    return render(request, 'open_now/business_specs.html', context)

def get_review(request):

    business_name = request.POST['business_name']
    b = Business.objects.get(business_name__startswith=business_name)

    review_text = request.POST['review_text']
    rating = request.POST['rating']
    b.review_set.create(review_text = review_text, rating = rating, user = request.user)
    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)


def get_hours(request):

    business_name = request.POST['store']
    b = Business.objects.get(business_name__startswith=business_name)

    weekday_from = request.POST['weekday_from']
    weekday_to = request.POST['weekday_to']
    from_hour = request.POST['from_hour']
    to_hour = request.POST['to_hour']


    b.openinghours_set.create(weekday_from = weekday_from, weekday_to = weekday_to, from_hour = from_hour,
                              to_hour = to_hour)

    next = request.POST.get('next', '/')
    return HttpResponseRedirect(next)



def location_view(request):

    # initial folium map focused on the center of the City of Charlottesville
    # center of US coords 40.619290458576074, -95.65487442647927
    m = folium.Map(width='100%', height='100%', location=get_center_coordinates(38.02931,-78.47668), zoom_start=13)
    m = m._repr_html_()

    form = LocationForm()
    if request.method == 'POST':
        form = LocationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('/open_now/map/display/')


    context = {
        'form': form,
        'map': m,
    }
    return render(request, 'open_now/location.html', context)


def map_view(request):

    locations = Location.objects.all()
    count = locations.count()
    lat = None
    lng = None

    if count > 1:
        # print("There is more than one current location")
        pass

    # set the current location to the last location in the database
    current_location = locations[count-1]

    # get all of the fields
    street_address = current_location.street_address
    address_2 = current_location.address_2
    city = current_location.city
    state = current_location.state
    postal_code = current_location.postal_code

    # create the properly formatted address or postal code
    # does not factor in alternate info
    address_or_postal_code = str(street_address) + ', ' + str(city) + ', ' + str(state) + ' ' + str(postal_code)

    # get the latitude and longitude for the current location
    client = GoogleMapsClient(api_key=GOOGLE_API_KEY, address_or_postal_code=address_or_postal_code)
    lat, lng = client.lat, client.lng
    pointA = (lat, lng)

    # print(lat, lng)

    # ---------------------------------------------------------------------------------------- #
    # folium map with current location marked
    m = folium.Map(width='100%', height='100%', location=get_center_coordinates(lat, lng), zoom_start=17)

    folium.Marker([lat, lng], tooltip=address_or_postal_code, popup='You are here', icon=folium.Icon(color='red')).add_to(m)


    form = SearchForm()
    if request.method == 'POST':
        form = SearchForm(request.POST)
        if form.is_valid():
            instance = form.save(commit=False)
            search_category = form.cleaned_data.get('search_category')
            radius = form.cleaned_data.get('radius')

        # perform the search based on a keywork ex: "Mexican Food" or "Bagels"
        # radius is in meters
        # results = client.search(keyword=search_category, radius=radius*1000, location=address_or_postal_code)


        # get all the businesses that have been submitted and perform a search using the google maps API
        businesses = Business.objects.all()
        count = businesses.count()

        for business in businesses:

            # make sure we are searching for the correct type of business
            if search_category == business.business_category:

                result = client.search(keyword=business.business_name, radius=radius*1000, location=address_or_postal_code)

                min_distance = 1000000
                index = -1
                lat_f = -1
                lng_f = -1
                rough_address_f = ''
                name_f = ''

                # for multiple locations of a business, get the closest one
                for i in range(len(result['results'])):

                    lat_result = result['results'][i]['geometry']['location']['lat']
                    lng_result = result['results'][i]['geometry']['location']['lng']
                    rough_address = result['results'][i]['vicinity']
                    name = result['results'][i]['name'] 
                    pointB = (lat_result, lng_result)

                    distance_km = calculate_distance(pointA, pointB)

                    if distance_km < min_distance:
                        min_distance = distance_km
                        index = i
                        lat_f = lat_result
                        lng_f = lng_result
                        rough_address_f = rough_address
                        name_f = name


                # print(result['results'][index]['name'], end="")
                # print(" " + result['results'][index]['vicinity'], end="")
                # print(" --> " +  str(distance_km))

                # mark it on the map
                link = f"/open_now/businesses/{business.business_name}/"
                test = folium.Popup('<a href="'+ link +'"target="window">'+ name_f + '</a>')

open_now/templates/open_now/archive_business_form.html
<!doctype html>
{% load socialaccount %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Homepage - OpenNow</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/starter-template/">



    <!-- Bootstrap core CSS -->
    <!-- using bootstrap CDN temporarily -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">OpenNow</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:business_list' %}">Businesses</a>
                </li>
                                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:business_form' %}">Submit a Business</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:forums' %}">Forums</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/uva-cs3240-s21/project-b-26">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        {% if user.is_authenticated %}
                        <h6 class="dropdown-header">Signed in as <strong>{{user.username}}</strong></h6>
                        {% else %}
                        <h6 class="dropdown-header">Signed in as <strong>guest</strong></h6>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item" href="{% url 'open_now:login' %}">Login</a></li>
                        <!-- ADD TEMPORARY LOGOUT FUNCTIONALITY HERE -->
                        <li><a class="dropdown-item" href="{% url 'open_now:login' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
            <form action="{% url 'open_now:search_result' %}" method="get">
                <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>

<main class="container" style="padding-top:5rem">

    <div class="starter-template text-center py-5 px-3">
<form action="/open_now/new-business/" method="post">
    {% csrf_token %}
<div class="form-group-column">
  <label for="business_name" class="form-label">Business Name:</label><br>
  <input type="text" class="form-control" id="business_name" name="business_name"><br>
  <label for="description" class="form-label">Description</label><br>
  <input type="text" class="form-control" id="description" name="description">
      <label for="phone_number" class="form-label">Phone Number</label><br>
  <input type="text" class="form-control" id="phone_number" name="phone_number">
     <label for="website" class="form-label">Website</label><br>
  <input type="text" class="form-control" id="website" name="website">
<label for="business_category">Choose a category:</label>
  <select id="business_category" name="business_category">
    <option value="REST">Restaurant</option>
    <option value="SHOP">Retail</option>
    <option value="GYM">Gym or Workout</option>
    <option value="NONE">Other or Unspecified</option>
  </select><br>
<a href="{% url 'open_now:create_businessimage' %}">Upload Image</a>
<p></p>
    <button type="submit" class="btn btn-primary" value="submit">Submit!</button>
    </div>

</main><!-- /.container -->


<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>

<!-- js bundle script for bootstrap-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

open_now/templates/open_now/archive_new_discussion.html
<!doctype html>
{% load socialaccount %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Homepage - OpenNow</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/starter-template/">



    <!-- Bootstrap core CSS -->
    <!-- using bootstrap CDN temporarily -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">OpenNow</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:business_list' %}">Businesses</a>
                </li>
                                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:business_form' %}">Submit a Business</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:forums' %}">Forums</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:map' %}">Map</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/uva-cs3240-s21/project-b-26">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        {% if user.is_authenticated %}
                        <h6 class="dropdown-header">Signed in as <strong>{{user.username}}</strong></h6>
                        {% else %}
                        <h6 class="dropdown-header">Signed in as <strong>guest</strong></h6>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item" href="{% url 'open_now:login' %}">Login</a></li>
                        <!-- ADD TEMPORARY LOGOUT FUNCTIONALITY HERE -->
                        <li><a class="dropdown-item" href="{% url 'open_now:login' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
            <form action="{% url 'open_now:search_result' %}" method="get">
                <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<main class="container" style="padding-top:5rem">
    <br><br><br><br><br>
<div>
    <style>
        form{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    
</div>
<form action="{% url 'open_now:new_discussion'%}" method="POST">
    {% csrf_token %}
    <input type="hidden" class="form-control" id="forum" name="forum" value={{f.id}}>
    <h5>Forum: {{f.topic}}</h5> 
    Discuss:
    <input type="text" class="form-control" id="discuss" name="discuss"><br>
    <input type="submit" class="btn btn-success" value="Submit">
    
</form>
</main>
<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
  
<!-- js bundle script for bootstrap-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

open_now/templates/open_now/archive_new_forum.html
<!doctype html>
{% load socialaccount %}
{% load static %}
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.80.0">
    <title>Homepage - OpenNow</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/starter-template/">



    <!-- Bootstrap core CSS -->
    <!-- using bootstrap CDN temporarily -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-BmbxuPwQa2lc/FVzBcNJ7UAyJxM6wuqIj61tLrc4wSX0szH/Ev+nYRRuWlolflfl" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }
    </style>


    <!-- Custom styles for this template -->
    <link href="{% static 'css/starter-template.css' %}" rel="stylesheet">
</head>
<body>

<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">OpenNow</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarsExampleDefault" aria-controls="navbarsExampleDefault" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarsExampleDefault">
            <ul class="navbar-nav me-auto mb-2 mb-md-0">
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:home' %}">Home</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:business_list' %}">Businesses</a>
                </li>
                                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:business_form' %}">Submit a Business</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:forums' %}">Forums</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" aria-current="page" href="{% url 'open_now:map' %}">Map</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="https://github.com/uva-cs3240-s21/project-b-26">About</a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="dropdown01" data-bs-toggle="dropdown" aria-expanded="false">Account</a>
                    <ul class="dropdown-menu" aria-labelledby="dropdown01">
                        {% if user.is_authenticated %}
                        <h6 class="dropdown-header">Signed in as <strong>{{user.username}}</strong></h6>
                        {% else %}
                        <h6 class="dropdown-header">Signed in as <strong>guest</strong></h6>
                        {% endif %}
                        <div class="dropdown-divider"></div>
                        <li><a class="dropdown-item" href="{% url 'open_now:login' %}">Login</a></li>
                        <!-- ADD TEMPORARY LOGOUT FUNCTIONALITY HERE -->
                        <li><a class="dropdown-item" href="{% url 'open_now:login' %}">Logout</a></li>
                    </ul>
                </li>
            </ul>
            <form action="{% url 'open_now:search_result' %}" method="get">
                <input class="form-control me-2" name="query" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </div>
    </div>
</nav>
<main class="container" style="padding-top:5rem">
    <br><br><br><br><br>
<div>
    <style>
        form{
            border:4px solid black;
            margin: 0 auto;
            padding: 40px;
            width: fit-content;
        }
    </style>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.0/css/bootstrap.min.css" integrity="sha384-9aIt2nRpC12Uk9gS9baDl411NQApFmC26EwAOH8WgZl5MYYxFfc+NcPb1dKGj7Sk" crossorigin="anonymous"0>
    
</div>
<form action="{% url 'open_now:new_forum' %}" method="POST">
    {% csrf_token %}
    {{form.as_p}}
    <input type="submit" class="btn btn-success" value="Submit">
</form>
</main>

<script src="../assets/dist/js/bootstrap.bundle.min.js"></script>
  
<!-- js bundle script for bootstrap-->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.bundle.min.js" integrity="sha384-b5kHyXgcpbZJO/tY9Ul7kGkf1S0CWuKcCD38l8YkeH8z8QjE0GmW1gYU5S9FOnJ0" crossorigin="anonymous"></script>
</body>
</html>

open_now/templates/open_now/map.html
{% extends "open_now/base.html" %}
{% load static %}
{% load crispy_forms_tags %}
{% block page-title %}
Business Map Search - OpenNow
{% endblock page-title %}

{% block header-no-div %}

<div class="container-fluid" style="padding-top:3rem">
    <div class="row">
        <div class="col-4" style="padding-top:2rem">
            <div class="container">
                <h1>Nearby Business Map Search</h1>
                <p class="lead">Enter a business category and kilometer radius to <strong>search for nearby businesses.</strong></p>
            </div>
            <div class="container">
                <form method="POST" class="row g-3">
                    {% csrf_token %}
                    <div class="col-md-8">
                        {{form.search_category | as_crispy_field}}
                    </div>
                    <div class="col-md-4">
                        {{form.radius | as_crispy_field}}
                    </div>
                    <div class="col-12">
                        <a href="{% url 'open_now:map' %}" class="btn btn-info text-white" role="button">Reset Address</a>
                        <input type="submit" class="btn btn-success" value="Search Nearby Businesses">
                    </div>
                </form>
            </div>
            <div class="container py-2">
                <p class="small">This product includes GeoLite2 data created by MaxMind, available from
                    <a href="https://www.maxmind.com">https://www.maxmind.com</a></p>
            </div>
        </div>
        <div class="col-8 g-0">
            {{map|safe}}
        </div>
    </div>
</div>

{% if request.POST and distance is not None %}
<script>
    $(window).on('load', function() {
        $('#exampleModal').modal('show')
    })
</script>
{% endif %}
{% endblock header-no-div %}

{% block top-header %}
{# Map Search #}
{% endblock top-header %}

{% block p-lead %}
{# Enter a valid address and <strong>search for businesses by map.</strong> #}
{% endblock p-lead %}

{% block upper-body %}

{% endblock upper-body %}
{% block body %}
{% endblock body %}